export const RULE_SECTIONS = [
  {
    id: 'overview',
    type: 'rule',
    eyebrow: 'Game basics',
    title: 'Goal and players',
    paragraphs: [
      'Wizard is a trick-taking game for 3 to 6 players. The goal is to predict exactly how many tricks you will win in each round.',
      'Correct bids earn points. Missing a bid costs points. The player with the highest cumulative score after the final round wins.',
    ],
  },
  {
    id: 'deck',
    type: 'rule',
    eyebrow: 'The deck',
    title: 'Cards and ranking',
    bullets: [
      '52 suited cards: Ace is high and 2 is low.',
      '4 Wizards: higher than every suited card.',
      '4 Jesters: lower than every other card unless only Jesters are played.',
    ],
  },
  {
    id: 'dealing',
    type: 'rule',
    eyebrow: 'Setup',
    title: 'Rounds, dealing, and dealer',
    paragraphs: [
      'Deal 1 card to each player in round 1, 2 cards in round 2, and continue adding one card per round. The dealer rotates clockwise after every round.',
    ],
    bullets: [
      '3 players: 20 rounds',
      '4 players: 15 rounds',
      '5 players: 12 rounds',
      '6 players: 10 rounds',
    ],
  },
  {
    id: 'trump',
    type: 'rule',
    eyebrow: 'Before bidding',
    title: 'Choosing trump',
    bullets: [
      'Turn over the top card of the remaining deck. Its suit is trump for the round.',
      'If a Wizard is revealed, the dealer chooses the trump suit.',
      'If a Jester is revealed, the round has no trump.',
      'When every card has been dealt, including the standard final round, there is no card to reveal and therefore no trump.',
    ],
  },
  {
    id: 'bidding',
    type: 'rule',
    eyebrow: 'Bidding',
    title: 'Predicting tricks',
    paragraphs: [
      'Starting with the player immediately after the dealer, each player bids clockwise. A bid can be any number from zero through the number of cards in the hand.',
      'The Hook is in play when the total bids equal the number of tricks available. In that case, at least one player must miss their bid.',
    ],
  },
  {
    id: 'play',
    type: 'rule',
    eyebrow: 'Playing',
    title: 'Playing a trick',
    bullets: [
      'The player after the dealer leads the first trick. The winner of each trick leads the next.',
      'Players must follow the led suit when able.',
      'A Wizard or Jester may be played at any time, even when the player can follow suit.',
      'If a Jester is led, the first suited card played establishes the led suit.',
    ],
  },
  {
    id: 'winning',
    type: 'rule',
    eyebrow: 'Playing',
    title: 'Winning a trick',
    bullets: [
      'The first Wizard played wins. Later Wizards do not beat it.',
      'If no Wizard is played, the highest trump wins.',
      'If there is no Wizard or trump, the highest card of the led suit wins.',
      'A Jester loses to every other card. If only Jesters are played, the first Jester wins.',
    ],
  },
  {
    id: 'scoring',
    type: 'rule',
    eyebrow: 'Scoring',
    title: 'Calculating points',
    paragraphs: [
      'If the bid is correct, score 20 points plus 10 points for every trick won.',
      'If the bid is incorrect, lose 10 points for each trick above or below the bid.',
    ],
    examples: [
      'Bid 2 and win 2: 20 + (10 × 2) = 40 points.',
      'Bid 3 and win 1: 2 tricks short = −20 points.',
      'Bid 0 and win 0: 20 points.',
    ],
  },
  {
    id: 'faq-special',
    type: 'faq',
    eyebrow: 'FAQ',
    title: 'Can I play a Wizard or Jester when I can follow suit?',
    paragraphs: ['Yes. Wizards and Jesters can always be played, regardless of the led suit or the cards in your hand.'],
  },
  {
    id: 'faq-wizard-trump',
    type: 'faq',
    eyebrow: 'FAQ',
    title: 'What if a Wizard is turned up for trump?',
    paragraphs: ['The dealer chooses one of the four suits as trump for that round.'],
  },
  {
    id: 'faq-no-trump',
    type: 'faq',
    eyebrow: 'FAQ',
    title: 'When is there no trump?',
    paragraphs: ['There is no trump when a Jester is revealed or when no undealt card remains to reveal, as in the standard final round.'],
  },
  {
    id: 'faq-hook',
    type: 'faq',
    eyebrow: 'FAQ',
    title: 'What is The Hook?',
    paragraphs: ['The Hook describes a round where total bids equal the tricks available. Since every trick must be won, at least one player cannot finish on their exact bid.'],
  },
  {
    id: 'faq-miss',
    type: 'faq',
    eyebrow: 'FAQ',
    title: 'What happens when I miss my bid?',
    paragraphs: ['Lose 10 points for every trick above or below your bid. For example, bidding 3 and winning 1 scores −20.'],
  },
  {
    id: 'faq-regular-deck',
    type: 'faq',
    eyebrow: 'FAQ',
    title: 'Can I play with a regular deck?',
    paragraphs: ['A house-rule substitute is possible: use Jokers as Wizards and the four 2s as Jesters. A dedicated 60-card Wizard deck is preferred.'],
  },
  {
    id: 'faq-correction',
    type: 'faq',
    eyebrow: 'FAQ',
    title: 'What if a bid or trick was entered incorrectly?',
    paragraphs: ['Use Correct bids or Correct tricks before saving the round. Once saved, the round appears as read-only history in the complete scorecard.'],
  },
]
